table Dim_Date
	lineageTag: eebe7cf0-8d0b-4eff-8703-74a1b8bab8d1

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e2cc5e8f-16e9-465b-8bb4-ff90fe83b821
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f5729c74-246b-4b34-a10b-44b77a048039
			defaultHierarchy: LocalDateTable_24883653-7966-4bac-88c0-7fb59b8393ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 66b166ec-ff6a-4084-94e2-7bea3819ee46
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 01c6f258-7b41-40cd-b6db-a3bd1991d609
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 2e28f80b-a8ab-441d-b9a1-374ad47a6565
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Inserted Year" = Table.AddColumn(#"Removed Duplicates", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([date]), type text)
				in
				    #"Inserted Month Name"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

