table Fact_Sales
	lineageTag: 00de0341-89de-404c-bb9b-82d8fe33b115

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 697a772b-9c77-4edf-8242-c51eed61cef6

	measure 'Total Quantity' =
			
			SUM(Fact_Sales[quantity])
		formatString: 0
		lineageTag: f9d474ad-138c-4d7c-8fe3-ae4bb6e37be9

	measure 'Average Order Value' =
			
			DIVIDE(
			    [Total Sales],
			    DISTINCTCOUNT(Fact_Sales[sale_id])
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d0b26a35-0f55-412b-aa41-784d121ed84d

	measure 'Sales YoY %' =
			
			VAR CurrentSales = [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        SAMEPERIODLASTYEAR(Dim_Date[date])
			    )
			RETURN
			    DIVIDE(
			        CurrentSales - PreviousSales,
			        PreviousSales
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 83d719cb-db64-4d95-92c7-c7150fbd3d22

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(Dim_Date[date]),
			        Dim_Date[date] <= MAX(Dim_Date[date])
			    )
			)
		lineageTag: 9502dbac-3fd4-4657-bb13-b0f7200748aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'City Sales Rank' =
			
			RANKX(
			    ALL(Dim_City[city]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: e6331466-4f8f-4937-ade4-af67c05f0bab

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 553c08cd-738d-40e7-addf-28bb40ef4b9f
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e41c87c-d42c-4fb9-a428-f80a0c4d27b1
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 19758658-d8c3-4c16-84f2-6c76e59e391f
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: ae1d02b7-ffa8-4311-83f7-f9b33401b0c8
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 349f56b0-972c-44e8-8891-6ac8a07876e6
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 34247e69-7a20-4be7-98f4-4fe12c0ac37d
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 4c6ce1ec-4540-40e5-b77d-ae5fa7296c8d
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 0b17f4cf-54f4-438b-be42-e267087d3567
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 7f7c5889-2734-4768-bad5-22d9fdeb2ceb
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Kaviya\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

